### ISSUE TITLE
Error after upgrading to this build Windows 10 v18636.815

### ISSUE THREAD

**Issue by Beav1810** [docker/docker.github.io#10708]
Diag ID = 95C91D10-1389-41E3-B0BA-71EFC25D3DFD/20200426190633

Docker.Core.DockerException:
Docker.Core.Backend.BackendDestroyException:
Unable to create Hyper-V VM: Hyper-V encountered an error trying to access an object on computer 'KH-LT-20509' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-MobyLinuxVM, <No file>: line 388
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: Hyper-V encountered an error trying to access an object on computer 'KH-LT-20509' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
  at New-MobyLinuxVM, <No file>: line 388
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.HyperV.Create(Settings settings)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     Hyper-V encountered an error trying to access an object on computer 'KH-LT-20509' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
     
         Microsoft.Virtualization.Client.Management.ServerObjectDeletedException:
         Hyper-V encountered an error trying to access an object on computer 'KH-LT-20509' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
            at Microsoft.Virtualization.Client.Management.Server.LoadOSInfo()
            at Microsoft.HyperV.PowerShell.VirtualizationObjectLocator.PrepareServerConnections(Server server, Boolean allowDownlevelServers)
            at Microsoft.HyperV.PowerShell.VirtualizationObjectLocator.GetServer(String computerName)
            at Microsoft.HyperV.PowerShell.ExceptionHelper.TryWithLogging[TInput,TOutput](Func`2 function, TInput input, IOperationWatcher operationWatcher)
         
              Microsoft.Management.Infrastructure.CimException:
              Not found 
                 at Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1.MoveNext()
                 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                 at Microsoft.Virtualization.Client.Management.Server.LoadOSInfo()
              
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. If you need support, you can try the Docker Community Forums. If you believe there is a bug in the application, please create an issue in the application repo. If there is an issue in the documentation, please let us know.
