### ISSUE TITLE
window 10 cmd run docker -v error

### ISSUE THREAD

**Issue by huang858563** [docker/docker.github.io#11912]
panic: Invalid standard handle identifier: 4294967286

goroutine 1 [running]:
github.com/docker/cli/vendor/github.com/Azure/go-ansiterm/winterm.GetStdFile(0xfffffff6, 0xc0001e4588, 0x154)
        /go/src/github.com/docker/cli/vendor/github.com/Azure/go-ansiterm/winterm/ansi.go:173 +0x1f3
github.com/docker/cli/vendor/github.com/moby/term/windows.NewAnsiReader(0xfffffff6, 0xc00000000f, 0x20d46c0)
        /go/src/github.com/docker/cli/vendor/github.com/moby/term/windows/ansi_reader.go:34 +0x36
github.com/docker/cli/vendor/github.com/moby/term.StdStreams(0xc000096340, 0xc0004abeb8, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/cli/vendor/github.com/moby/term/term_windows.go:75 +0x1eb
github.com/docker/cli/cli/command.NewDockerCli(0x0, 0x0, 0x0, 0x19b926c, 0x1b4f0a0, 0xc000113e60)
        /go/src/github.com/docker/cli/cli/command/cli.go:473 +0x1a7
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:291 +0x4b

**Comment by asongent** [comment]
Hello!
Docker has been working quite okay on my Windows 10 until now. I have been receiving the above output each time I run a "docker run -d -p 80:80 docker/getting-started" command on CMD. I uninstalled, downloaded and installed the latest version but still having same issue. I have reached out to several communities for solution, but didn't find anything helpful. 
Any help to resolve this issue will be much appreciated.

**Comment by gdhy9064** [comment]
I encountered the same problems on CMD. However, I have tried running the command in other terminals such as Git Bash and Cygwin64 Terminal, it works.

**Comment by thaJeztah** [comment]
Looks like this is an issue with the docker cli; this issue tracker is for the docker documentation only.

Let me transfer this ticket to the https://github.com/docker/cli repository
