### ISSUE TITLE
Build error in Getting-Started guide using a M1 Macbook

### ISSUE THREAD

**Issue by janikdotzel** [docker/docker.github.io#15394]
### Problem description & location

File: [get-started/09_image_best.md#layer-caching](https://github.com/docker/docker.github.io/blob/master/get-started/09_image_best.md#layer-caching)

Running the command `docker build -t getting-started .` from step 3 results in the following error:
<div class="panel panel-default">
<pre><code>
[+] Building 13.3s (13/14)
 => [internal] load build definition from Dockerfile                                                                       0.0s
 => => transferring dockerfile: 204B                                                                                       0.0s
 => [internal] load .dockerignore                                                                                          0.0s
 => => transferring context: 52B                                                                                           0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                                 1.7s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io                                                           0.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:443aab4ca21183e069e7d8b2dc68006594f40bddf1b15bbd83f5137bd9  0.0s
 => [internal] load build definition from Dockerfile                                                                       0.0s
 => [internal] load .dockerignore                                                                                          0.0s
 => [internal] load metadata for docker.io/library/node:12-alpine                                                          0.0s
 => CACHED [1/5] FROM docker.io/library/node:12-alpine                                                                     0.0s
 => [internal] load build context                                                                                          0.5s
 => => transferring context: 3.26kB                                                                                        0.5s
 => [2/5] WORKDIR /app                                                                                                     0.0s
 => [3/5] COPY package.json yarn.lock ./                                                                                   0.0s
 => ERROR [4/5] RUN yarn install --production                                                                             10.7s
------
 > [4/5] RUN yarn install --production:
#13 0.331 yarn install v1.22.18
#13 0.382 [1/4] Resolving packages...
#13 0.426 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
#13 0.429 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^3.0.0"
#13 0.538 [2/4] Fetching packages...
#13 9.083 [3/4] Linking dependencies...
#13 9.602 [4/4] Building fresh packages...
#13 10.59 error /app/node_modules/sqlite3: Command failed.
#13 10.59 Exit code: 1
#13 10.59 Command: node-pre-gyp install --fallback-to-build
#13 10.59 Arguments:
#13 10.59 Directory: /app/node_modules/sqlite3
#13 10.59 Output:
#13 10.59 node-pre-gyp info it worked if it ends with ok
#13 10.59 node-pre-gyp info using node-pre-gyp@0.11.0
#13 10.59 node-pre-gyp info using node@12.22.12 | linux | arm64
#13 10.59 node-pre-gyp WARN Using request for node-pre-gyp https download
#13 10.59 node-pre-gyp info check checked for "/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node" (not found)
#13 10.59 node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
#13 10.59 node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
#13 10.59 node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
#13 10.59 node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.2 and node@12.22.12 (node-v72 ABI, musl) (falling back to source compile with node-gyp)
#13 10.59 node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
#13 10.59 gyp info it worked if it ends with ok
#13 10.59 gyp info using node-gyp@3.8.0
#13 10.59 gyp info using node@12.22.12 | linux | arm64
#13 10.59 gyp info ok
#13 10.59 gyp info it worked if it ends with ok
#13 10.59 gyp info using node-gyp@3.8.0
#13 10.59 gyp info using node@12.22.12 | linux | arm64
#13 10.59 gyp ERR! configure error
#13 10.59 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#13 10.59 gyp ERR! stack     at PythonFinder.failNoPython (/app/node_modules/node-gyp/lib/configure.js:484:19)
#13 10.59 gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/configure.js:406:16)
#13 10.59 gyp ERR! stack     at F (/app/node_modules/which/which.js:68:16)
#13 10.59 gyp ERR! stack     at E (/app/node_modules/which/which.js:80:29)
#13 10.59 gyp ERR! stack     at /app/node_modules/which/which.js:89:16
#13 10.59 gyp ERR! stack     at /app/node_modules/isexe/index.js:42:5
#13 10.59 gyp ERR! stack     at /app/node_modules/isexe/mode.js:8:5
#13 10.59 gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
#13 10.59 gyp ERR! System Linux 5.10.104-linuxkit
#13 10.59 gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
#13 10.59 gyp ERR! cwd /app/node_modules/sqlite3
#13 10.59 gyp ERR! node -v v12.22.12
#13 10.59 gyp ERR! node-gyp -v v3.8.0
#13 10.59 gyp ERR! not ok
#13 10.59 node-pre-gyp ERR! build error
#13 10.59 node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#13 10.59 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
#13 10.59 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
#13 10.59 node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
#13 10.59 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
#13 10.59 node-pre-gyp ERR! System Linux 5.10.104-linuxkit
#13 10.59 node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#13 10.59 node-pre-gyp ERR! cwd /app/node_modules/sqlite3
#13 10.59 node-pre-gyp ERR! node -v v12.22.12
#13 10.59 node-pre-gyp ERR! node-pre-gyp -v v0.11.0
#13 10.59 node-pre-gyp ERR! not ok
#13 10.59 Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#13 10.59 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install --production]: exit code: 1
</code></pre>
</div>

### Suggestions for a fix

It is very likely that the problem is related to M1 macbooks as they are missing some modules.

In Chapter [02_our_app.md#build-the-apps-container-image](https://github.com/docker/docker.github.io/blob/master/get-started/02_our_app.md#build-the-apps-container-image) there is an additional layer used in the Dockerfile.
Layer: `RUN apk add --no-cache python2 g++ make`

Adding this particular Layer to the docs would result in a successful build.

**Comment by janikdotzel** [comment]
PR: #15395
