### ISSUE TITLE
Feedback for: engine/installation/linux/centos.md

### ISSUE THREAD

**Issue by JonathanAaron** [docker/docker.github.io#1596]
File: [engine/installation/linux/centos.md](https://docs.docker.com/engine/installation/linux/centos/)

I received and error when trying to add a repo.

`[user1 ~]$ sudo yum-config-manager --add-repo https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo
Loaded plugins: product-id, rhnplugin
This system is receiving updates from RHN Classic or Red Hat Satellite.
adding repo from: https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo
grabbing file https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo to /etc/yum.repos.d/docker.repo
Traceback (most recent call last):
  File "/usr/bin/yum-config-manager", line 218, in <module>
    result  = grabber.urlgrab(url, filename=destname, copy_local=True)
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1172, in urlgrab
    return self._retry(opts, retryfunc, url, filename)
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1064, in _retry
    r = apply(func, (opts,) + args, {})
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1157, in retryfunc
    fo = PyCurlFileObject(url, filename, opts)
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1258, in __init__
    self._do_open()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1589, in _do_open
    self._set_opts()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1413, in _set_opts
    self.curl_obj.setopt(pycurl.CAPATH, opts.ssl_ca_cert)
TypeError: invalid arguments to setopt`

**Comment by mstanleyjones** [comment]
Can you please try with the instructions as currently published?

**Comment by mstanleyjones** [comment]
No response in nearly 3 months. Please reopen if you have more info.

**Comment by chris03** [comment]
Had the same error, it's (was) a bug with yum/urlgrabber: https://bugzilla.redhat.com/show_bug.cgi?id=1023595
As a workaround (when you can't update yum) just get the file manually:
```
wget https://download.docker.com/linux/centos/docker-ce.repo
yum-config-manager --add-repo docker-ce.repo
```
