### ISSUE TITLE
Debian install instructions fail

### ISSUE THREAD

**Issue by QJKX** [docker/docker.github.io#1977]
File: [engine/installation/linux/debian.md](https://docs.docker.com/engine/installation/linux/debian/), CC: @mstanleyjones 

Step 3 doesn't work on this stretch box.
```
# add-apt-repository \
>        "deb https://apt.dockerproject.org/repo/ \
>        debian-$(lsb_release -cs) \
>        main"
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Debian/stretch
```

**Comment by bdwill** [comment]
Documentation appears to be fixed already. Distro template is included.

**Comment by mstanleyjones** [comment]
Thanks @bdwill !
