### ISSUE TITLE
Cannot get nltk to work with Docker

### ISSUE THREAD

**Issue by griff4692** [docker/docker.github.io#7715]
### Problem description
I am trying to create a very simple Docker container to run on codalab for deep learning project.

Here are my requirements:
```
python version==3.6
allennlp==0.7.1
pytorch==0.4.1
nltk==3.3
```
Here is my DockerFile right now.
```
FROM anibali/pytorch:no-cuda
FROM allennlp/allennlp:v0.7.1
RUN pip install nltk
python -c "import nltk; nltk.download(['punkt'])"
```
When I run sent_tokenizer for nltk I get the following error message on codalab:
```
  import imp
/usr/local/lib/python3.6/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'tree_lstm.TreeLSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'allennlp.modules.elmo.Elmo' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'allennlp.modules.scalar_mix.ScalarMix' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'answer_verifier.AnswerVerifier' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "src/end_to_end.py", line 104, in <module>
    main(sys.argv[1], sys.argv[2])
  File "src/end_to_end.py", line 54, in main
    sentences = sent_tokenize(passage)
  File "/usr/local/lib/python3.6/site-packages/nltk/tokenize/__init__.py", line 94, in sent_tokenize
    tokenizer = load('tokenizers/punkt/{0}.pickle'.format(language))
  File "/usr/local/lib/python3.6/site-packages/nltk/data.py", line 836, in load
    opened_resource = _open(resource_url)
  File "/usr/local/lib/python3.6/site-packages/nltk/data.py", line 954, in _open
    return find(path_, path + ['']).open()
  File "/usr/local/lib/python3.6/site-packages/nltk/data.py", line 675, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource �[93mpunkt�[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  �[31m>>> import nltk
  >>> nltk.download('punkt')
  �[0m
  Searched in:
    - '/0xc31ca1c95f9d4846910c711b6cdef845/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
```
Any ideas on how to fix this?  I am new to Docker and have been stuck for days on this issue.

Also, any advice on how to improve the dockerfile and make it as simple as possible. My code has no other dependencies since I don't need GPU/cuda because I am just evaluating a trained PyTorch model.

**Comment by traci-morrison** [comment]
Thank you for your feedback. However, it looks like your issue is not about Docker documentation, but that you may be having trouble with Docker itself. Please file a Docker support ticket or check out https://forums.docker.com/ to see if you can find a solution.

If this really is a documentation issue and I have misunderstood,please reopen it with more information.
