### ISSUE TITLE
Maybe Python issue mismatch on swarm tutorial site

### ISSUE THREAD

**Issue by atekka85epam** [docker/docker.github.io#8834]
File: [engine/swarm/stack-deploy.md](https://docs.docker.com/engine/swarm/stack-deploy/)

Hello!

While following the instructions on this site, "Deploy a stack to a swarm", I am getting the error:
web_1    |  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
web_1    |  * Restarting with stat
web_1    | Traceback (most recent call last):
web_1    |   File "app.py", line 13, in <module>
web_1    |     app.run(host="0.0.0.0", port=8000, debug=True)
web_1    |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 944, in run
web_1    |     run_simple(host, port, self, **options)
web_1    |   File "/usr/local/lib/python3.4/site-packages/werkzeug/serving.py", line 1007, in run_simple
web_1    |     run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
web_1    |   File "/usr/local/lib/python3.4/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
web_1    |     sys.exit(reloader.restart_with_reloader())
web_1    |   File "/usr/local/lib/python3.4/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
web_1    |     exit_code = subprocess.call(args, env=new_environ, close_fds=False)
web_1    |   File "/usr/local/lib/python3.4/subprocess.py", line 534, in call
web_1    |     with Popen(*popenargs, **kwargs) as p:
web_1    |   File "/usr/local/lib/python3.4/subprocess.py", line 856, in __init__
web_1    |     restore_signals, start_new_session)
web_1    |   File "/usr/local/lib/python3.4/subprocess.py", line 1464, in _execute_child
web_1    |     raise child_exception_type(errno_num, err_msg)
web_1    | OSError: [Errno 8] Exec format error
stackdemo_web_1 exited with code 1

after step :
docker-compose up -d

Do I messed up something or maybe python 3.4-alpine is no longer the right choose for this one  ?

I am using Win10, docker for windows Version 2.0.0.3 (31259).

Thanks

**Comment by atekka85epam** [comment]
On Ubuntu I did not exprerienced this problem only on Win10 + docker for windows.
